### ISSUE TITLE
Gettinng Catch error

### ISSUE THREAD

**Issue by saviomartin** [WebDevSimplified/Nodejs-Passport-Login#4]
This is the error I got 
```
acer@acer-Acer-one-14-Z476:~/Desktop/new$ node server.js 
/home/acer/Desktop/new/server.js:38
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
And My Code there has no problem, I think so.
```
app.post('/register', (req, res) => {
    try {
        const hashedPassword = bcrypt.hash(req.body.password, 10)
        users.push({
          id: Date.now().toString(),
          name: req.body.name,
          email: req.body.email,
          password: hashedPassword
        })
        res.redirect('/login')
    } catch {
      res.redirect('/register')
    }
    console.log(users)
})
```
Please help me.😓

**Comment by 3chospirits** [comment]
it is `catch(err){` not `catch{`
```
app.post('/register', (req, res) => {
    try {
        const hashedPassword = bcrypt.hash(req.body.password, 10)
        users.push({
          id: Date.now().toString(),
          name: req.body.name,
          email: req.body.email,
          password: hashedPassword
        })
        res.redirect('/login')
    } catch (err){
      res.redirect('/register')
    }
    console.log(users)
})
```

**Comment by yaonn** [comment]
```
try {
} catch (error) {
  concole.log(error)
  res.redirect('/register')
}
```
maybe try this?

**Comment by saviomartin** [comment]
Thanks, it helped
